// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptbfvpdhjbcedduoqlxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0YmZ2cGRoamJjZWRkdW9xbHh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNTE4ODksImV4cCI6MjA1ODcyNzg4OX0.vHcYiKUFi4OaPB-OwIhafLLJVA7zJq7uX4Iq-52lDmc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);